3_sem/db/dblabapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'dblabapp'

urlpatterns = [
            url(r'^$', views.index, name='index'),
            url(r'^drivers$', views.list_drivers, name='list_drivers'),
            url(r'^logs/upload_text$', views.upload_text, name = 'upload_text'),
            url(r'^logs/process_upload_text$', views.process_upload_text, name = 'process_upload_text'),
            url(r'^logs/upload_file$', views.upload_file, name = 'upload_file'),
            url(r'^logs/process_upload_file$', views.process_upload_file, name = 'process_upload_file'),
            url(r'^log_sessions/list_all$', views.list_log_sessions, name = 'list_sessions'),
            url(r'^log_sessions/(?P<session_id>[0-9]+)', views.list_log_entries, name = 'list_log_entries'),
            url(r'^log_sessions/compare/choose$', views.compare_choose, name = 'compare_choose'),
            url(r'^log_sessions/compare/validate$', views.compare_validate, name = 'compare_validate'),
            url(r'^log_sessions/compare/(?P<session_1>[0-9]+)/(?P<session_2>[0-9]+)$', views.compare_show, name = 'compare_show'),
            url(r'^log_sessions/delete/(?P<session_id>[0-9]+)$', views.delete_session, name = 'delete_session'),
            ]

3_sem/db/dblabapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class DriverEntry(models.Model):
    driver_name = models.CharField(max_length = 200)

    def __str__(self):
        return '( ' + self.driver_name + ' )'

class LogSession(models.Model):
    date = models.DateField(auto_now_add = True)
    comment = models.CharField(max_length = 200)

    def __str__(self):
        return '[' + str(self.date) + '] ' + self.comment 

class LogEntry(models.Model):
    time = models.FloatField()
    driver = models.ForeignKey(DriverEntry)
    message = models.CharField(max_length = 200)
    logSession = models.ForeignKey(LogSession)

    def __str__(self):
        return '[' + str(self.time) + ']' + str(self.driver) + ':' + self.message

3_sem/db/dblabapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.db.models import Q

from .models import DriverEntry 
from .parser import *

import cx_Oracle

def index(request):
    return render(request, 'home/index.html')

def list_drivers(request):
    drivers_list = DriverEntry.objects.all()
    return render(request, 'drivers/list_all.html', {'drivers_list' : drivers_list})

def list_log_sessions(request):
    sessions_list = LogSession.objects.order_by('date')
    return render(request, 'log_sessions/list_all.html', {'sessions_list' : sessions_list})

def list_log_entries(request, session_id):
    entries_list = LogEntry.objects.filter(logSession = session_id).order_by('time')
    session = LogSession.objects.get(id = session_id)
    session_info = str(session)
    return render(request, 'log_entries/list_all.html', {'entries_list' : entries_list, 
                                                         'session_info' : session_info })

def compare_choose(request):
    sessions_list = LogSession.objects.order_by('date')
    return render(request, 'compare/choose.html', {'sessions_list' : sessions_list})

def compare_validate(request):
    selected = request.POST.getlist('checks')
    if (len(selected) != 2):
        return HttpResponse('You must select exactly two sessions')
    else:
        return redirect(reverse('dblabapp:compare_show', args = (selected[0], selected[1])))

def compare_show(request, session_1, session_2):
    session_1_obj = LogSession.objects.get(id = session_1)
    session_1_info = str(session_1_obj)
    entries_list_1 = LogEntry.objects.filter(logSession = session_1).order_by('time')
    
    session_2_obj = LogSession.objects.get(id = session_2)
    session_2_info = str(session_2_obj)

    entries = LogEntry.objects.filter(Q(logSession = session_1) | Q(logSession = session_2)).order_by('time')

    divided_entries = []
    for e in entries:
        if e.logSession == session_1:
            divided_entries.append([1, e])
        else:
            divided_entries.append([2, e])

    return render(request, 'compare/show.html', {'entries_list' : entries,
                                                'session_1_info' : session_1_info,
                                                'session_2_info' : session_2_info,
                                                'session_1' : session_1_obj, 
                                                'session_2' : session_2_obj})

def upload_text(request):
    return render(request, 'upload/upload_text.html')

def process_upload_text(request):
    log_text = request.POST['log_text']
    comment = request.POST['comment']
    try:
        parseText(log_text, comment)
        return redirect(reverse('dblabapp:index'))
    except:
        return HttpResponse('Could not parse log, check your file')

def upload_file(request):
    return render(request, 'upload/upload_file.html')

def process_upload_file(request):
    log_text = request.FILES['log_text'].read()
    comment = request.POST['comment']
    try:
        parseText(log_text, comment)
        return redirect(reverse('dblabapp:index'))
    except Exception as e:
        return HttpResponse('Error in line ' + str(e))

def delete_session(request, session_id):
    LogSession.objects.get(id = session_id).delete() # trigger takes care of the entries
    return redirect(reverse('dblabapp:list_sessions'))

# Create your views here.

3_sem/db/dblabapp/templates/compare/choose.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<style type="text/css">
td
{
    padding:0 25px 0 15px;
}
</style>

<h1> Choose two log sessions to compare </h1>

<form action="{% url 'dblabapp:compare_validate' %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <th>Date</th>
            <th>Comment</th>
            <th>Link</th>
            <th>Compare</th>
        </tr>
        {% for session in sessions_list %}
        <tr>
            <td> {{session.date|date:'d M Y'}} </td>
            <td> {{session.comment}} </td>
            <td> <a href="{% url 'dblabapp:list_log_entries' session.id %}">link</a></td>
            <td> <input name="checks" type="checkbox" value="{{session.id}}"></td>
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Compare">
</form>

3_sem/db/dblabapp/templates/compare/show.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<style type="text/css">
td
{
    padding:0 25px 0 15px;
}

.blue_entry 
{
    color: #0D3D56;
}

.red_entry
{
    color: #C02F1D;
}

</style>

<h1>Comparison of session {{session_1_info}} (in blue) and {{session_2_info}} (in red) </h1>

<table>
    <tr>
        <th>Session</th>
        <th>Time</th>
        <th>Driver</th>
        <th>Message</th>
    </tr>
    {% for entry in entries_list %}
    <tr class={% if entry.logSession == session_1 %}"blue_entry" {% else %}"red_entry"{% endif %}>
        <td> {{entry.logSession}} </td>
        <td> {{entry.time}} </td>
        <td> {{entry.driver}} </td>
        <td> {{entry.message}} </td>
    </tr>
    {% endfor %}

</table>

3_sem/db/dblabapp/templates/drivers/list_all.html
{% if drivers_list %}
<h1> The list of all drivers: </h2>
<ul>
    {% for driver in drivers_list %}
    <li>{{ driver.driver_name }}</li>
    {% endfor %}
</ul>
{% else %}
<p>No drivers are available.</p>
{% endif %}

3_sem/db/dblabapp/templates/home/index.html
<h1> Welcome to dmesg analyser </h2>
<ul>
    <li>
        <a href="{% url 'dblabapp:upload_text' %}">Upload log text</a>
    </li>
    <li>
        <a href="{% url 'dblabapp:upload_file' %}">Upload log file</a>
    </li>
    <li>
        <a href="{% url 'dblabapp:list_drivers' %}">View all drivers</a>
    </li>
    <li>
        <a href="{% url 'dblabapp:list_sessions' %}">View all recorded sessions</a>
    </li>
    <li>
        <a href="{% url 'dblabapp:compare_choose' %}">Compare two sessions</a>
    </li>
</ul>

3_sem/db/dblabapp/templates/log_entries/list_all.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<style type="text/css">
td
{
    padding:0 25px 0 15px;
}
</style>

<h1>Log entries for session {{session_info}}</h1>

<table>
    <tr>
        <th>Time</th>
        <th>Driver</th>
        <th>Message</th>
    </tr>
    {% for entry in entries_list %}
    <tr>
        <td> {{entry.time}} </td>
        <td> {{entry.driver}} </td>
        <td> {{entry.message}} </td>
    </tr>
    {% endfor %}

</table>

3_sem/db/dblabapp/templates/log_sessions/list_all.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<style type="text/css">
td
{
    padding:0 25px 0 15px;
}
</style>

<h1>List of all recorded sessions:</h1>

<table>
    <tr>
        <th>Date</th>
        <th>Comment</th>
        <th>Link</th>
        <th>Delete</th>
    </tr>
    {% for session in sessions_list %}
    <tr>
        <td> {{session.date|date:'d M Y'}} </td>
        <td> {{session.comment}} </td>
        <td> <a href="{% url 'dblabapp:list_log_entries' session.id %}">link</a></td>
        <td> <a href="{% url 'dblabapp:delete_session' session.id %}">delete</a></td>
    </tr>
    {% endfor %}

</table>

3_sem/db/dblabapp/templates/upload/upload_file.html
<h1>Paste your log here</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'dblabapp:process_upload_file' %}" method="post" id="form" enctype="multipart/form-data">
{% csrf_token %}
    <p> Log: </p>
    <input type="file" form="form"  value="log_text" name="log_text" id="log_text" />
    <p> Comment: </p>
    <input type="text" name="comment" id="comment" value="" />
    <input type="submit" value="Send" />
</form>

3_sem/db/dblabapp/templates/upload/upload_text.html
<h1>Paste your log here</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'dblabapp:process_upload_text' %}" method="post" id="form">
{% csrf_token %}
    <p> Log: </p>
    <textarea form="form" cols="180" rows="40" name="log_text" id="log_text"></textarea>
    <p> Comment: </p>
    <input type="text" name="comment" id="comment" value="" />
    <input type="submit" value="Send" />
</form>