4_sem/appWWW/appWWW/appWWW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('elections.urls')),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
]

4_sem/appWWW/appWWW/elections/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from rest_framework import routers
from rest_framework.authtoken import views as rest_views

from . import views

app_name = 'elections'

router = routers.DefaultRouter()
router.register(r'gmina', views.GminaViewSet)
router.register(r'powiat', views.PowiatViewSet)
router.register(r'wojewodztwo', views.WojewodztwoViewSet)
router.register(r'vote', views.VoteViewSet)
router.register(r'candidate', views.CandidateViewSet)
router.register(r'kraj', views.KrajViewSet)

rest_api = [
    url(r'^', include(router.urls)),
    url(r'^authtoken/$', rest_views.ObtainAuthToken.as_view()),
    url(r'^login/$', views.rest_login), 
    url(r'^gmina/search/(?P<pattern>[^/]+)/', views.GminaSearchView.as_view()),
]

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^search/gmina/$', views.search_gmina, name='search_gmina'),

    url(r'^results/$', views.index, name='kraj'),

    url(r'^results/(?P<wojewodztwo_slug>[^/]+)/$',
        views.wojewodztwo, name='wojewodztwo'),

    url(r'^results/(?P<wojewodztwo_slug>[^/]+)/(?P<powiat_slug>[^/]+)/$',
        views.powiat, name='powiat'),

    url(r'^results/(?P<wojewodztwo_slug>[^/]+)/(?P<powiat_slug>[^/]+)/(?P<gmina_slug>[^/]+)/$',
        views.gmina, name='gmina'),

    url(r'^results/(?P<wojewodztwo_slug>[^/]+)/(?P<powiat_slug>[^/]+)/(?P<gmina_slug>[^/]+)/edit/$',
        views.edit_gmina, name='edit_gmina'),

    url(r'^api/', include(rest_api)),
]

4_sem/appWWW/appWWW/elections/models.py
from django.db import models
from django.db.models import *
from django.template.defaultfilters import slugify

from django.conf import settings
from django.urls import reverse

from django.db.models.signals import post_save
from django.dispatch import receiver

from rest_framework.authtoken.models import Token

from channels.binding import Binding
from channels.channel import Group


import elections.utility as utility


class Region(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Region, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def getBallots(self):
        pass

    def getVoters(self):
        pass

    def getTurnout(self):
        return round(self.getBallots() / self.getVoters() * 100, 2)

    def getDistribution(self):
        return utility.buildVotesDistributionDict(self.buildQ())

    class Meta:
        abstract = True


class Kraj(Region):
    subunit_str = 'Województwo'

    def subunit(self):
        return Wojewodztwo

    def getBallots(self):
        return Gmina.objects.all().aggregate(Sum('ballots'))['ballots__sum']

    def getVoters(self):
        return Gmina.objects.all().aggregate(Sum('voters'))['voters__sum']

    def buildQ(self):
        return Q()

    def path(self):
        return reverse('elections:kraj')


class Wojewodztwo(Region):
    subunit_str = 'Powiat'
    kraj = models.ForeignKey(Kraj)

    def subunit(self):
        return Powiat

    def getBallots(self):
        p = Powiat.objects.filter(wojewodztwo=self)
        res = 0
        for e in p:
            res += Gmina.objects.filter(powiat=e).aggregate(
                Sum('ballots'))['ballots__sum']
        return res

    def getVoters(self):
        p = Powiat.objects.filter(wojewodztwo=self)
        res = 0
        for e in p:
            res += Gmina.objects.filter(powiat=e).aggregate(
                Sum('voters'))['voters__sum']
        return res

    def buildQ(self):
        return Q(wojewodztwo=self)

    def path(self):
        return reverse('elections:wojewodztwo', args=[self.slug])

class Powiat(Region):
    wojewodztwo = models.ForeignKey(Wojewodztwo)

    subunit_str = 'Gmina'

    def subunit(self):
        return Gmina

    def getBallots(self):
        return Gmina.objects.filter(powiat=self).aggregate(Sum('ballots'))['ballots__sum']

    def getVoters(self):
        return Gmina.objects.filter(powiat=self).aggregate(Sum('voters'))['voters__sum']

    def buildQ(self):
        return Q(powiat=self)

    def path(self):
        return reverse('elections:powiat', args=[self.wojewodztwo.slug, self.slug])


class Gmina(Region):
    powiat = models.ForeignKey(Powiat)
    code = models.IntegerField()
    ballots = models.IntegerField(default=0)
    voters = models.IntegerField(default=0)

    def buildQ(self):
        return Q(gmina=self)

    def getBallots(self):
        return self.ballots

    def getVoters(self):
        return self.voters

    def votes_dict(self):
        return utility.buildVotesDict(self)

    def __str__(self):
        return self.name

    def path(self):
        return reverse('elections:gmina', args=[self.powiat.wojewodztwo.slug,
                                                self.powiat.slug,
                                                self.slug])

    def edit_path(self):
        return reverse('elections:edit_gmina', args=[self.powiat.wojewodztwo.slug,
                                                     self.powiat.slug,
                                                     self.slug])


class Candidate(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Vote(models.Model):
    wojewodztwo = models.ForeignKey(Wojewodztwo)
    gmina = models.ForeignKey(Gmina)
    powiat = models.ForeignKey(Powiat)
    candidate = models.ForeignKey(Candidate)
    votes = models.IntegerField()

    def __str__(self):
        return 'In {0}, {1}, {2}, {3} people voted for {4}'.format(self.wojewodztwo,
                                                                   self.gmina,
                                                                   self.powiat,
                                                                   self.votes,
                                                                   self.candidate)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

4_sem/appWWW/appWWW/elections/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseForbidden
from rest_framework import viewsets
from django.contrib import auth

from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import detail_route
from rest_framework import status
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework import generics

from . import utility, serializers
from .models import *
from . import html_render as html


def index(request):
    return HttpResponse(html.index(request))


def wojewodztwo(request, wojewodztwo_slug):
    return HttpResponse(html.wojewodztwo(request, wojewodztwo_slug))


def powiat(request, wojewodztwo_slug, powiat_slug):
    return HttpResponse(html.powiat(request, wojewodztwo_slug, powiat_slug))


def gmina(request, wojewodztwo_slug, powiat_slug, gmina_slug):
    return HttpResponse(html.gmina(request, wojewodztwo_slug, powiat_slug, gmina_slug))


def edit_gmina(request, wojewodztwo_slug, powiat_slug, gmina_slug):
    g = utility.getGmina(wojewodztwo_slug, powiat_slug, gmina_slug)
    return render(request, 'client_render/edit_gmina.html', {'pk': g.pk})


def search_gmina(request):
    pattern = request.GET.get('pattern', '')
    return render(request, 'client_render/search.html', {'pattern': pattern})


class GminaViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Gmina.objects.all()
    serializer_class = serializers.GminaSerializer

    @detail_route(methods=['get', 'put'], permission_classes=[IsAuthenticated])
    def vote_stats(self, request, pk=None):
        if request.method == 'GET':
            g = self.get_object()
            serializer = serializers.GminaStatsSerializer(g)
            return Response(serializer.data)
        else:
            data = JSONParser().parse(request)
            serializer = serializers.GminaStatsSerializer(data=data)
            if serializer.is_valid():
                g = self.get_object()
                serializer.update(g, serializer.validated_data)
                return Response('all\'s good', status.HTTP_200_OK)
            return Response(serializer.errors, status.HTTP_400_BAD_REQUEST)


class GminaSearchView(generics.ListAPIView):
    serializer_class = serializers.GminaSerializer

    def get_queryset(self):
        pattern = self.kwargs['pattern']
        return Gmina.objects.filter(name__contains=pattern)


class PowiatViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Powiat.objects.all()
    serializer_class = serializers.PowiatSerializer

    @detail_route(methods=['get'])
    def gmina_set(self, request, pk=None):
        powiat = self.get_object()
        result = powiat.gmina_set
        serializer = serializers.GminaSerializer(
            result, context={'request': request}, many=True)
        return Response(serializer.data)


class WojewodztwoViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Wojewodztwo.objects.all()
    serializer_class = serializers.WojewodztwoSerializer

    @detail_route(methods=['get'])
    def powiat_set(self, request, pk=None):
        wojewodztwo = self.get_object()
        result = wojewodztwo.powiat_set
        serializer = serializers.PowiatSerializer(
            result, context={'request': request}, many=True)
        return Response(serializer.data)


class VoteViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Vote.objects.all()
    serializer_class = serializers.VoteSerializer


class CandidateViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Candidate.objects.all()
    serializer_class = serializers.CandidateSerializer


class KrajViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Kraj.objects.all()
    serializer_class = serializers.KrajSerializer


def rest_login(request):
    return render(request, 'client_render/login.html')

4_sem/appWWW/appWWW/elections/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"/>
        <link href="/static/style.css" media="screen and (min-width: 850px)" rel="stylesheet" type="text/css"/>
        <link href="/static/style_mobile.css" media="screen and (max-width: 851px)" rel="stylesheet" type="text/css"/>
        <title> Wybory 2000: {{ title }}</title>
    </head>
    <body>
        <h2> Wyniki wyborów 2000 roku </h2>
        <h2> {{ title }} </h2>
        {% if user.is_authenticated %}
        <a href="{% url 'elections:logout' %}">Log out</a>
        {% else %}
        <a href="{% url 'elections:login' %}">Log in</a>
        {% endif %}

        <form method="get" action="{% url 'elections:search_gmina' %}">
            {% csrf_token %}
            {{ search_form.as_p }}
            <button type="submit">Submit</button>
        </form>

        {% block content %}
        {% endblock %}
    </body>
</html>

4_sem/appWWW/appWWW/elections/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock %}

4_sem/appWWW/appWWW/elections/templates/gmina.html
{% include "stats.html" %}

{% if user.is_authenticated %}
<a href="{{ region_info.edit_path }}">Edytuj</a>
{% endif %}

4_sem/appWWW/appWWW/elections/templates/kraj.html
{% extends 'base.html' %}

{% block content %}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
google.load('visualization', '1', {'packages': ['geochart']});
google.charts.load('current', {'packages':['corechart']});

google.setOnLoadCallback(drawMarkersMap);
//google.charts.setOnLoadCallback(drawChart);

function slugify(text)
{
    str = text.toString().toLowerCase()
        .replace(/\s+/g, '-')           // Replace spaces with -
        .replace(/\-\-+/g, '-')         // Replace multiple - with single -
        .replace(/^-+/, '')             // Trim - from start of text
        .replace(/-+$/, '');            // Trim - from end of text
    // remove accents, swap ñ for n, etc
    var from = "ąężźóćłśń/_,:;";
    var to   = "aezzoclsn-----";
    for (var i=0, l=from.length ; i<l ; i++) {
        str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
    }
    return str;
}

function drawMarkersMap() {
    {% autoescape off %}
    var jsonData = `{{ data }}`
    {% endautoescape %}

    var data = new google.visualization.DataTable(jsonData);

    var options = {
        region: 'PL',
        dataMode: 'regions',
        displayMode: 'regions',
        resolution: 'provinces',
        legend: 'none',
        enableRegionInteractivity: 'true',
        sizeAxis: {minSize:5,  maxSize: 5},
        colorAxis: {colors: ['#0B2762']}
    };

    var chart = new google.visualization.GeoChart(document.getElementById('map_chart'));

    google.visualization.events.addListener(chart, 'select', function () {
        var selection = chart.getSelection();
        if (selection.length > 0) {
            window.location = './' + slugify(data.getValue(selection[0].row, 0));
        }
    });

    chart.draw(data, options);
};


function drawChart() {
    var data = new google.visualization.DataTable(jsonData);

    var options = {
        title: 'Głosy'
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
};

</script>

    <div class="general_stats">
        <p>
        Uprawnionych: {{ region_info.getVoters }}
        </p>
        <p>
        Kart ważnych: {{ region_info.getBallots }}
        </p>
        <p>
        Frekwencja: {{ region_info.turnout | floatformat:"-2" }}%
        </p>
    </div>

    <div id="charts">

        <div id="map_chart"></div>

        <div class="responsive_hide">
            <div class="chart">
                {% for stat in candidates_stats %}
                <div class="bar_wrap">
                    <div class="bar" style="height: {{ stat.2 }}%;">
                        <div>
                            {{ stat.1 | floatformat:"-2" }}%
                        </div>
                    </div>
                    <div class="legend">
                        {{ stat.0 }}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="desktop_hide">
            <div class="chart">
                {% for stat in candidates_stats %}
                <div class="bar_wrap">
                    <div class="bar" style="width: {{ stat.2 }}%;">
                        <div>
                            {{ stat.1 | floatformat:"-2" }}%
                        </div>
                    </div>
                    <div class="legend">
                        {{ stat.0 }}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>

    <table>
        <tr>
            <th>
                {{ unit }}
            </th>
            <th>
                Statystyka
            </th>
            <th class="responsive_hide">
                Uprawnionych
            </th>
            <th class="responsive_hide">
                Kart ważnych
            </th>
            <th>
                Frekwencja
            </th>
        </tr>
        {% for w in regions_data %}
        <tr>
            <td>
                <a href="{{ w.path }}">{{ w.name }}</a>
            </td>
            <td>
                <div class="horizontal_bar_chart">
                    {% for bar in w.bar %}
                    <div class="horizontal_bar_element" style="background-color: {{ bar.2 }}; flex-grow: {{ bar.1 }};">
                        <div class="horizontal_bar_tooltip">
                            {{ bar.0 }}
                            {{ bar.1 | floatformat:"-2" }}%
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </td>
            <td class="responsive_hide">
                {{ w.getVoters }}
            </td>
            <td class="responsive_hide">
                {{ w.getBallots }}
            </td>
            <td>
                {{ w.turnout | floatformat:"-2" }}%
            </td>
        </tr>
        {% endfor %}

    </table>

    {% endblock %}

4_sem/appWWW/appWWW/elections/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>

{% endblock %}

4_sem/appWWW/appWWW/elections/templates/search_gmina.html
{% extends 'base.html' %}

{% block content %}

{% for result in results %}
<p>
<a href="{{ result.path }}">{{result.name}}</a>
</p>
{% endfor %}

{% endblock %}

4_sem/appWWW/appWWW/elections/templates/stats.html
{% extends 'base.html' %}

{% block content %}

{% if data %}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
google.load('visualization', '1', {'packages': ['geochart']});
google.charts.load('current', {'packages':['corechart']});

google.setOnLoadCallback(drawMarkersMap);
//google.charts.setOnLoadCallback(drawChart);

function slugify(text)
{
    str = text.toString().toLowerCase()
        .replace(/\s+/g, '-')           // Replace spaces with -
        .replace(/\-\-+/g, '-')         // Replace multiple - with single -
        .replace(/^-+/, '')             // Trim - from start of text
        .replace('ł', '')               // remove ł
        .replace(/-+$/, '');            // Trim - from end of text
    // remove accents, swap ñ for n, etc
    var from = "ąężźóćłśń/_,:;";
    var to   = "aezzoclsn-----";
    for (var i=0, l=from.length ; i<l ; i++) {
        str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
    }
    return str;
}

function drawMarkersMap() {
    {% autoescape off %}
    var jsonData = `{{ data }}`
    {% endautoescape %}

    var data = new google.visualization.DataTable(jsonData);

    var options = {
        region: 'PL',
        dataMode: 'regions',
        displayMode: 'regions',
        resolution: 'provinces',
        legend: 'none',
        enableRegionInteractivity: 'true',
        sizeAxis: {minSize:5,  maxSize: 5},
        colorAxis: {colors: ['#0B2762']}
    };

    var chart = new google.visualization.GeoChart(document.getElementById('map_chart'));

    google.visualization.events.addListener(chart, 'select', function () {
        var selection = chart.getSelection();
        if (selection.length > 0) {
            window.location = './' + slugify(data.getValue(selection[0].row, 0));
        }
    });

    chart.draw(data, options);
};


function drawChart() {
    var data = new google.visualization.DataTable(jsonData);

    var options = {
        title: 'Głosy'
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
};

</script>

    {% endif %}

    <div class="general_stats">
        <p>
        Uprawnionych: {{ region_info.getVoters }}
        </p>
        <p>
        Kart ważnych: {{ region_info.getBallots }}
        </p>
        <p>
        Frekwencja: {{ region_info.turnout | floatformat:"-2" }}%
        </p>
    </div>

    <div id="charts">

        {% if data %}
        <div id="map_chart"></div>
        {% endif %}


        <div class="responsive_hide">
            <div class="chart">
                {% for stat in candidates_stats %}
                <div class="bar_wrap">
                    <div class="bar" style="height: {{ stat.2 }}%;">
                        <div>
                            {{ stat.1 | floatformat:"-2" }}%
                        </div>
                    </div>
                    <div class="legend">
                        {{ stat.0 }}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="desktop_hide">
            <div class="chart">
                {% for stat in candidates_stats %}
                <div class="bar_wrap">
                    <div class="bar" style="width: {{ stat.2 }}%;">
                        <div>
                            {{ stat.1 | floatformat:"-2" }}%
                        </div>
                    </div>
                    <div class="legend">
                        {{ stat.0 }}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>

    {% if regions_data %}
    <table>
        <tr>
            <th>
                {{ unit }}
            </th>
            <th>
                Statystyka
            </th>
            <th class="responsive_hide">
                Uprawnionych
            </th>
            <th class="responsive_hide">
                Kart ważnych
            </th>
            <th>
                Frekwencja
            </th>
        </tr>
        {% for w in regions_data %}
        <tr>
            <td>
                <a href="{{ w.path }}">{{ w.name }}</a>
            </td>
            <td>
                <div class="horizontal_bar_chart">
                    {% for bar in w.bar %}
                    <div class="horizontal_bar_element" style="background-color: {{ bar.2 }}; flex-grow: {{ bar.1 }};">
                        <div class="horizontal_bar_tooltip">
                            {{ bar.0 }}
                            {{ bar.1 | floatformat:"-2" }}%
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </td>
            <td class="responsive_hide">
                {{ w.getVoters }}
            </td>
            <td class="responsive_hide">
                {{ w.getBallots }}
            </td>
            <td>
                {{ w.turnout | floatformat:"-2" }}%
            </td>
        </tr>
        {% endfor %}

    </table>
    {% endif %}

    {% endblock %}